### ISSUE TITLE
Datasource MVP

### ISSUE THREAD

**Issue by sunker** [grafana/redshift-datasource#1]
This epic outlines all the features that need to be implemented for the plugin MVP, according the [Redshift plugin addendum](https://drive.google.com/file/d/1ZGA26jhM7_tj79o4Yg03iZZnSlw9dRcd/view?usp=sharing). 

- [x] Authentication: Same type of auth options as all the other AWS data source plugins - AWS SDK Default, Keys & Secrets, Credentials file auth and Workspace IAM Auth.
- [x] Authentication: Possibility to disable/enable options depending on context. For example, Credentials file auth should not be enabled in AMG.
- [x] QueryEditor: Raw SQL editor built on top of Monaco. 
- [x] QueryEditor: SQL syntax highlighting according to spec in the Monaco Redshift language definition: https://github.com/microsoft/monaco-languages/blob/main/src/redshift/redshift.ts 
- [x] QueryEditor: Editor autocomplete with suggestions for macros, template variables and parts of the schema such as tables etc
- [x] Templating: Possibility to use single-valued and multi-valued template variables in the SQL query.
- [x] Templating: Support template variable queries.
- [x] Macros: Macros can be used in queries to simplify syntax and to allow for dynamic parts, like date range filters. Which ones to use is still TBD.
- [x] Annotations: Possibility to overlay the graph with annotation events. The annotation query editor willshoulduse the same raw sql editor component as the metric query editor does.
- [x] Alerting: Easily set alerts on queries you’ve created. (no actual implementation on our side - just need to make sure it works)
- [x] #44
- [x] Curated dashboard: We should, together with the Redshift team, create one dashboard that demonstrates the features of the plugin.
