### ISSUE TITLE
1.1.x

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/redshift-datasource#72]
- [ ] https://github.com/grafana/redshift-datasource/issues/42
- [ ] https://github.com/grafana/redshift-datasource/issues/52
- [x] https://github.com/grafana/redshift-datasource/issues/61

**Comment by sarahzinger** [comment]
Gunna close this if that's ok!
